from FileLoader import FileLoader
from HowManyMedalsByCountry import how_many_medals_by_country

fl = FileLoader()
df = fl.load("./athlete_events.csv")

def get_medals_by_country(country):
    print(f"{country}:")
    medals = how_many_medals_by_country(df, country)
    for key, value in medals.items():
        print(f"  {key}: {value}")

get_medals_by_country("Estonia")
get_medals_by_country("France")
get_medals_by_country("Cuba")
get_medals_by_country("Spain")
get_medals_by_country("Chile")
get_medals_by_country("Cameroon")
get_medals_by_country("Turkey")
get_medals_by_country("Greece")
get_medals_by_country("Mexico")
get_medals_by_country("Hungary")
get_medals_by_country("Chad")
get_medals_by_country("Bahrain")
get_medals_by_country("Pakistan")
get_medals_by_country("Iraq")
get_medals_by_country("Kuwait")
get_medals_by_country("United Arab Republic")
get_medals_by_country("Egypt")
get_medals_by_country("Lebanon")
get_medals_by_country("Nigeria")
get_medals_by_country("Qatar")
get_medals_by_country("Malaysia")
get_medals_by_country("Azerbaijan")
get_medals_by_country("Tanzania")
get_medals_by_country("Jordan")
get_medals_by_country("Sudan")
get_medals_by_country("Tunisia")
get_medals_by_country("Libya")
get_medals_by_country("Palestine")
get_medals_by_country("Comoros")
get_medals_by_country("Brunei")
get_medals_by_country("Ethiopia")
get_medals_by_country("Uzbekistan")
get_medals_by_country("Tajikistan")
get_medals_by_country("Unified Team")
get_medals_by_country("Kyrgyzstan")
get_medals_by_country("Japan-1")
get_medals_by_country("East Germany")
get_medals_by_country("West Germany")
get_medals_by_country("Monaco")
get_medals_by_country("Fornebo")
get_medals_by_country("Israel")
get_medals_by_country("Sri Lanka")
get_medals_by_country("Armenia")
get_medals_by_country("Cote d'Ivoire")
get_medals_by_country("Benin")
get_medals_by_country("Latvia")
get_medals_by_country("Costa Rica")
get_medals_by_country("Panama")

